name: 📦🚀 Build & deploy Android app for an environment

on:
  release:
    types:
      - published
jobs:
  deployAndroid:
    name: 🤖📦🚀 Build & deploy Android release
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3
      - name: ⚙️ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
        id: java
      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: 'stable'
          cache: true
        id: flutter
      - name: 🔐 Retrieve base64 keystore and decode it to a file
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "android-keystore.jks"
          fileDir: "${{ github.workspace }}/"
          encodedString: ${{ secrets.KEYSTORE_FILE_BASE64 }}
      - name: 📝🔐 Create keystore.properties file
        env:
          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/app/android/key.properties
        run: |
          echo 'storeFile=${{ github.workspace }}/android-keystore.jks' > $KEYSTORE_PROPERTIES_PATH
          echo 'keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'storePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
      - name: ⚙️ Setup Melos
        uses: bluefireteam/melos-action@v2
      - name: ⚙️ Install dependencies for all packages
        run: melos build:pub_get:all
      - name: 🤖📦 Create Android release
        run: |
          flutter build appbundle --release
          flutter build apk --split-per-abi --release
      - name: 🤖🚀 Upload to GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/app/outputs/flutter-apk/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
