name: 📦🚀 Build & deploy Android app for an environment

on:
  release:
    types:
      - published
jobs:
  deployAndroid:
    permissions: write-all
    name: 🤖📦🚀 Build & deploy Android release
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3
      - name: ⚙️ Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "19.x"
          cache: 'gradle'
          distribution: 'adopt'
        id: java
      - name: 🔐 Retrieve base64 keystore and decode it to a file
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "android-keystore.jks"
          fileDir: "${{ github.workspace }}/"
          encodedString: ${{ secrets.KEYSTORE_FILE_BASE64 }}
      - name: 📝🔐 Create keystore.properties file
        env:
          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/app/key.properties
        run: |
          echo "storeFile=${{ github.workspace }}/android-keystore.jks" > $KEYSTORE_PROPERTIES_PATH
          echo "keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> $KEYSTORE_PROPERTIES_PATH
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> $KEYSTORE_PROPERTIES_PATH
          echo "keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}" >> $KEYSTORE_PROPERTIES_PATH
      - uses: olegtarasov/get-tag@v2 # that generate $GIT_TAG_NAME env
        id: tagName
        with:
          tagRegex: 'internal-v([0-9]+.[0-9]+.[0-9]+\+[0-9]+)' # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      - name: 🤖📦 Create Android release
        run: |
          ./gradlew app:assembleRelease
      - name: 🤖🚀 Upload to GitHub release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/app/outputs/flutter-apk/*;build/app/outputs/bundle/release/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
